name: 'run-doctests'
description: 'Run `doctest(MyPkg; fix=true)`'
author: 'Eric P. Hanson and contributors'

branding:
  icon: 'package'
  color: 'green'

inputs:
  ### Required inputs
  package:
    description: 'Name of the package to run doctests for'
    required: true
  project:
    description: 'Value passed to the --project flag. The default value is "docs"'
    default: 'docs'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Fix doctests
      run: julia --code-coverage --project=${{ inputs.project }} "$GITHUB_ACTION_PATH"/run_doctests.jl
      shell: bash
        
